# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

name = "bundle"
client_id = "cf52aa45d96fb49cf44081f3f4d68fa7"
application_url = "https://shopify.dev/apps/default-app-home"
embedded = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_cart_transforms"

[auth]
redirect_urls = [ "https://shopify.dev/apps/default-app-home/api/auth" ]

[webhooks]
api_version = "2023-07"

[pos]
embedded = false

[build]
dev_store_url = "umesh-dev-store.myshopify.com"
